config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'persons/profile'

  get 'timer' => 'timer#home'

  resources :routes

  root 'routes#index'

  get 'persons/profile', as: 'user_root'

end

app/models/route.rb
class Route < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_route, only: [:show, :edit, :update, :destroy]


  # GET /routes
  # GET /routes.json
  def index
    @routes = Route.all
  end

  # GET /routes/1
  # GET /routes/1.json
  def show
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes
  # POST /routes.json
  def create
    @route = Route.new(route_params)

    respond_to do |format|
      if @route.save
        format.html { redirect_to @route, notice: 'Route was successfully created.' }
        format.json { render :show, status: :created, location: @route }
      else
        format.html { render :new }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url, notice: 'Route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_params
      params.require(:route).permit(:name, :time_do)
    end
end

app/controllers/timer_controller.rb
class TimerController < ApplicationController
	 before_filter :authenticate_user!
  def home

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/timer_helper.rb
module TimerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<title>HoursManager</title>
	 <link href="/assets/logo.ico" rel="shortcut icon" type="image/x-icon" />
	<%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

</head>
<body>

    <header class="navbar navbar-fixed-top navbar-inverse">

	<% if user_signed_in? %>
	    <span>Hello, <%= current_user.email %></span>
	<% end %>

      <div class="navbar-inner">
        <div class="container">
        	<img alt="Rails" src="/assets/logo.png" width="40" />
          <%= link_to "Hours Manager", root_path, id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Timers", timer_path %></li>
              <li><%= link_to "Routes", routes_path %></li>
    <% if user_signed_in? %>
	    <li><%= link_to 'Exit', destroy_user_session_path, :method => :delete %></li>
	<% else %>
	    <li><%= link_to 'Login', new_user_session_path %> or <%= link_to 'Register', new_user_registration_path %></li>
	<% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>

    <div class="container">
      <%= yield %>
    </div>
</body>
</html>

app/views/persons/profile.html.erb
<h1>Persons#profile</h1>
<p>Find me in app/views/persons/profile.html.erb</p>

app/views/routes/_form.html.erb
<%= form_for(@route) do |f| %>
  <% if @route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% @route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :time_do %><br>
    <%= f.number_field :time_do %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/routes/edit.html.erb
<h1>Editing Route</h1>

<%= render 'form' %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Routes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Time do</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= route.name %></td>
        <td><%= route.time_do %></td>
        <td><%= link_to 'Show', route %></td>
        <td><%= link_to 'Edit', edit_route_path(route) %></td>
        <td><%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Route', new_route_path %>

app/views/routes/new.html.erb
<h1>New Route</h1>

<%= render 'form' %>

<%= link_to 'Back', routes_path %>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @route.name %>
</p>

<p>
  <strong>Time do:</strong>
  <%= @route.time_do %>
</p>

<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>

app/views/timer/home.html.erb
<div class="content">
	<h1 id="timer_name">Pomodoro timer</h1>
	<h1 id="timer_index">00:00:00</h1>
	Select route:
	<input type="text" size="40">
	<button id="start" onclick="newTimer(1500,2,1);">Старт</button>
	<%= javascript_include_tag 'timer.js' %>
	
</div>